# Generated by Django 5.0.3 on 2024-03-26 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_name_profile_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='quick_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
