# Generated by Django 5.0.3 on 2024-04-01 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='social',
            new_name='social_github',
        ),
    ]
