# Generated by Django 5.0.3 on 2024-03-14 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_tag_product_created_product_vote_ratio_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Project',
        ),
    ]
