# Generated by Django 5.0.3 on 2024-03-14 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_rename_product_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='price',
        ),
    ]
