# Generated by Django 5.0.3 on 2024-03-19 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_remove_project_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, default='logo.png', null=True, upload_to=''),
        ),
    ]
